language: csharp
mono: none
dotnet: 3.1.410

services:
  - docker
before_install:
  - docker build -t acme-template:${TRAVIS_BUILD_NUMBER} ./buildcontainer
script:
  - docker run --rm --mount type=bind,src="$(pwd)",dst=/build acme-template:${TRAVIS_BUILD_NUMBER} test
